include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .cache/**
    - .dart_tool/**
    - build/**
    - fastlane/**
    - lib/bbcode/generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
