import CoreVideo
import Flutter
import UIKit

private final class KazumiPipVideoDelegate: NSObject, FlutterPlugin {
    weak var owner: KazumiPipPluginRegistry?

    static func register(with registrar: FlutterPluginRegistrar) {}

    func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        owner?.handleVideoCall(call, result: result)
    }
}

private final class KazumiPipTextureRegistry: NSObject, FlutterTextureRegistry {
    private let registry: FlutterTextureRegistry
    private let frameHandler: (CVPixelBuffer, Int64) -> Void
    private var textures: [Int64: FlutterTexture] = [:]

    init(registry: FlutterTextureRegistry, frameHandler: @escaping (CVPixelBuffer, Int64) -> Void) {
        self.registry = registry
        self.frameHandler = frameHandler
        super.init()
    }

    func register(_ texture: FlutterTexture) -> Int64 {
        let textureId = registry.register(texture)
        textures[textureId] = texture
        return textureId
    }

    func unregisterTexture(_ textureId: Int64) {
        textures.removeValue(forKey: textureId)
        registry.unregisterTexture(textureId)
    }

    func copyPixelBuffer(forTexture textureId: Int64) -> CVPixelBuffer? {
        // FlutterTexture returns a retained buffer; transfer that reference to ARC.
        textures[textureId]?.copyPixelBuffer()?.takeRetainedValue()
    }

    func textureFrameAvailable(_ textureId: Int64) {
        // media-kit calls this on the platform thread after completing each render.
        // Do not depend on copyPixelBuffer being called by Flutter in background.
        if let buffer = copyPixelBuffer(forTexture: textureId) {
            frameHandler(buffer, textureId)
        }
        registry.textureFrameAvailable(textureId)
    }
}

// Only media-kit's registrar receives the texture adapter. Other plugins use
// their original registrars, and plugin registration remains generated by Flutter.
private final class KazumiPipRegistrar: NSObject, FlutterPluginRegistrar {
    private let registrar: FlutterPluginRegistrar
    let textureRegistry: KazumiPipTextureRegistry
    weak var owner: KazumiPipPluginRegistry?

    init(registrar: FlutterPluginRegistrar, textureRegistry: KazumiPipTextureRegistry) {
        self.registrar = registrar
        self.textureRegistry = textureRegistry
        super.init()
    }

    func messenger() -> FlutterBinaryMessenger { registrar.messenger() }
    func textures() -> FlutterTextureRegistry { textureRegistry }
    var viewController: UIViewController? { registrar.viewController }
    func publish(_ value: NSObject) { registrar.publish(value) }

    func addMethodCallDelegate(_ delegate: FlutterPlugin, channel: FlutterMethodChannel) {
        owner?.videoDelegate = delegate
        let adapter = KazumiPipVideoDelegate()
        adapter.owner = owner
        registrar.addMethodCallDelegate(adapter, channel: channel)
    }

    func addApplicationDelegate(_ delegate: FlutterPlugin) {
        registrar.addApplicationDelegate(delegate)
    }

    func addSceneDelegate(_ delegate: FlutterSceneLifeCycleDelegate) {
        registrar.addSceneDelegate(delegate)
    }

    func register(_ factory: FlutterPlatformViewFactory, withId factoryId: String) {
        registrar.register(factory, withId: factoryId)
    }

    func register(_ factory: FlutterPlatformViewFactory, withId factoryId: String,
                  gestureRecognizersBlockingPolicy policy: FlutterPlatformViewGestureRecognizersBlockingPolicy) {
        registrar.register(factory, withId: factoryId, gestureRecognizersBlockingPolicy: policy)
    }

    func lookupKey(forAsset asset: String) -> String { registrar.lookupKey(forAsset: asset) }
    func lookupKey(forAsset asset: String, fromPackage package: String) -> String {
        registrar.lookupKey(forAsset: asset, fromPackage: package)
    }

    func valuePublished(byPlugin pluginKey: String) -> NSObject? {
        registrar.valuePublished(byPlugin: pluginKey)
    }
}

// Give the app access to media-kit's rendered frames through Flutter's public
// texture API, including when the Flutter rasterizer is suspended in background.
final class KazumiPipPluginRegistry: NSObject, FlutterPluginRegistry {
    private let registry: FlutterPluginRegistry
    private let frameHandler: (CVPixelBuffer, Int64) -> Void
    private var videoRegistrar: KazumiPipRegistrar?
    fileprivate var videoDelegate: FlutterPlugin?
    private var outputArguments: [String: [String: Any]] = [:]
    private var generations: [String: UInt] = [:]
    private var softwareHandles: Set<String> = []
    private var recreatingHandles: Set<String> = []
    private var restorationCompletions: [() -> Void] = []
    private var softwareRendering = false
    private var pendingRestore = false

    var videoOutputWillChange: ((Int64, @escaping (Bool) -> Void) -> Void)?
    var videoOutputDidChange: ((Int64, @escaping (Bool) -> Void) -> Void)?

    init(registry: FlutterPluginRegistry, frameHandler: @escaping (CVPixelBuffer, Int64) -> Void) {
        self.registry = registry
        self.frameHandler = frameHandler
        super.init()
        NotificationCenter.default.addObserver(self, selector: #selector(restoreIfForeground),
                                               name: UIApplication.didBecomeActiveNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(restoreIfForeground),
                                               name: UIScene.didActivateNotification, object: nil)
    }

    func registrar(forPlugin pluginKey: String) -> FlutterPluginRegistrar? {
        guard let registrar = registry.registrar(forPlugin: pluginKey) else { return nil }
        guard pluginKey == "MediaKitVideoPlugin" else { return registrar }
        let textures = KazumiPipTextureRegistry(registry: registrar.textures(), frameHandler: frameHandler)
        let adapter = KazumiPipRegistrar(registrar: registrar, textureRegistry: textures)
        adapter.owner = self
        videoRegistrar = adapter
        return adapter
    }

    func hasPlugin(_ pluginKey: String) -> Bool { registry.hasPlugin(pluginKey) }
    func valuePublished(byPlugin pluginKey: String) -> NSObject? {
        registry.valuePublished(byPlugin: pluginKey)
    }

    func copyPixelBuffer(forTexture textureId: Int64) -> CVPixelBuffer? {
        videoRegistrar?.textureRegistry.copyPixelBuffer(forTexture: textureId)
    }

    fileprivate func handleVideoCall(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        var forwardedCall = call
        if let args = call.arguments as? [String: Any], let handle = args["handle"] as? String {
            switch call.method {
            case "VideoOutputManager.Create":
                generations[handle] = (generations[handle] ?? 0) &+ 1
                outputArguments[handle] = args
                softwareHandles.remove(handle)
                let software = softwareRendering ||
                    (pendingRestore && UIApplication.shared.applicationState != .active)
                var configuration = args["configuration"] as? [String: Any] ?? [:]
                if software && configuration["enableHardwareAcceleration"] as? Bool == true {
                    softwareHandles.insert(handle)
                    var replacement = args
                    configuration["enableHardwareAcceleration"] = false
                    replacement["configuration"] = configuration
                    forwardedCall = FlutterMethodCall(methodName: call.method, arguments: replacement)
                }
            case "VideoOutputManager.SetSize":
                if var saved = outputArguments[handle] {
                    var configuration = saved["configuration"] as? [String: Any] ?? [:]
                    configuration["width"] = args["width"]
                    configuration["height"] = args["height"]
                    saved["configuration"] = configuration
                    outputArguments[handle] = saved
                }
            case "VideoOutputManager.Dispose":
                generations[handle] = (generations[handle] ?? 0) &+ 1
                outputArguments.removeValue(forKey: handle)
                softwareHandles.remove(handle)
            default:
                break
            }
        }
        videoDelegate?.handle?(forwardedCall, result: result)
    }

    // Recreate only the native video output. The mpv player, audio, source, playback
    // position, decoder and shader settings all remain owned by the same player.
    private func recreateOutput(_ handle: String, completion: @escaping (Bool) -> Void) {
        guard !recreatingHandles.contains(handle),
              let willChange = videoOutputWillChange,
              let didChange = videoOutputDidChange else { completion(false); return }
        recreatingHandles.insert(handle)
        let generation = generations[handle] ?? 0
        let finish: (Bool) -> Void = { ready in
            self.recreatingHandles.remove(handle)
            completion(ready)
            // Closing PiP may race with a software output still being created.
            // Revisit a successful transition that now needs foreground restoration.
            if ready && !self.softwareRendering && self.softwareHandles.contains(handle) &&
                UIApplication.shared.applicationState == .active {
                self.restoreIfForeground()
            }
            self.finishRestorationIfIdle()
        }
        let resume: (Bool) -> Void = { created in
            didChange(Int64(handle) ?? 0) { resumed in finish(created && resumed) }
        }
        // Freeing an active mpv render context forcibly disables video. Suspend
        // the current video track first, then resume it after the new texture is registered.
        willChange(Int64(handle) ?? 0) { suspended in
            guard suspended else { finish(false); return }
            guard self.outputArguments[handle] != nil,
                  generation == self.generations[handle] else { resume(false); return }
            let dispose = FlutterMethodCall(methodName: "VideoOutputManager.Dispose", arguments: ["handle": handle])
            self.videoDelegate?.handle?(dispose, result: { value in
                guard var args = self.outputArguments[handle],
                      generation == self.generations[handle],
                      !(value is FlutterError) else { resume(false); return }
                var configuration = args["configuration"] as? [String: Any] ?? [:]
                let software = self.softwareRendering || UIApplication.shared.applicationState != .active
                if software && configuration["enableHardwareAcceleration"] as? Bool == true {
                    configuration["enableHardwareAcceleration"] = false
                    self.softwareHandles.insert(handle)
                } else {
                    self.softwareHandles.remove(handle)
                }
                args["configuration"] = configuration
                let create = FlutterMethodCall(methodName: "VideoOutputManager.Create", arguments: args)
                self.videoDelegate?.handle?(create, result: { result in
                    // Dart waits for VideoController.id to change before restoring vid;
                    // media-kit's immediate Create reply precedes context initialization.
                    resume(!(result is FlutterError))
                })
            })
        }
    }

    func useSoftwareRendering(forHandle handle: Int64, completion: @escaping (Bool) -> Void) {
        let key = String(handle)
        guard let args = outputArguments[key], videoDelegate != nil else { completion(false); return }
        softwareRendering = true
        pendingRestore = false
        let configuration = args["configuration"] as? [String: Any] ?? [:]
        if configuration["enableHardwareAcceleration"] as? Bool != true || softwareHandles.contains(key) {
            completion(true)
            return
        }
        recreateOutput(key, completion: completion)
    }

    func restoreRendering(completion: @escaping () -> Void) {
        softwareRendering = false
        pendingRestore = !softwareHandles.isEmpty || !recreatingHandles.isEmpty
        restorationCompletions.append(completion)
        restoreIfForeground()
        finishRestorationIfIdle()
    }

    private func finishRestorationIfIdle() {
        guard recreatingHandles.isEmpty else { return }
        let completions = restorationCompletions
        restorationCompletions.removeAll()
        completions.forEach { $0() }
    }

    @objc private func restoreIfForeground() {
        guard !softwareRendering, UIApplication.shared.applicationState == .active else { return }
        pendingRestore = false
        for handle in softwareHandles {
            recreateOutput(handle) { _ in }
        }
    }

    deinit {
        NotificationCenter.default.removeObserver(self)
    }
}
