#import "KazumiPipPluginRegistry.h"

@interface KazumiPipPluginRegistry ()
@property(nonatomic, strong) NSObject<FlutterPlugin> *videoDelegate;
@property(nonatomic, strong) NSMutableDictionary<NSString *, NSDictionary *> *outputArguments;
@property(nonatomic, strong) NSMutableDictionary<NSString *, NSNumber *> *generations;
@property(nonatomic, strong) NSMutableSet<NSString *> *softwareHandles;
@property(nonatomic, strong) NSMutableSet<NSString *> *recreatingHandles;
@property(nonatomic, strong) NSMutableArray<void (^)(void)> *restorationCompletions;
@property(nonatomic) BOOL softwareRendering;
@property(nonatomic) BOOL pendingRestore;
- (void)handleVideoCall:(FlutterMethodCall *)call result:(FlutterResult)result;
- (void)restoreIfForeground;
- (void)finishRestorationIfIdle;
@end

@interface KazumiPipVideoDelegate : NSObject <FlutterPlugin>
@property(nonatomic, weak) KazumiPipPluginRegistry *owner;
@end

@implementation KazumiPipVideoDelegate
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {}
- (void)handleMethodCall:(FlutterMethodCall *)call result:(FlutterResult)result {
    [self.owner handleVideoCall:call result:result];
}
@end

@interface KazumiPipTextureRegistry : NSObject <FlutterTextureRegistry>
@property(nonatomic, strong) NSObject<FlutterTextureRegistry> *registry;
@property(nonatomic, strong) NSMutableDictionary<NSNumber *, NSObject<FlutterTexture> *> *textures;
@property(nonatomic, copy) void (^frameHandler)(CVPixelBufferRef, int64_t);
@end

@implementation KazumiPipTextureRegistry
- (int64_t)registerTexture:(NSObject<FlutterTexture> *)texture {
    int64_t textureId = [self.registry registerTexture:texture];
    self.textures[@(textureId)] = texture;
    return textureId;
}

- (void)unregisterTexture:(int64_t)textureId {
    [self.textures removeObjectForKey:@(textureId)];
    [self.registry unregisterTexture:textureId];
}

- (void)textureFrameAvailable:(int64_t)textureId {
    // media-kit calls this on the platform thread after completing each render.
    // Do not depend on copyPixelBuffer being called by Flutter in background.
    CVPixelBufferRef buffer = [self.textures[@(textureId)] copyPixelBuffer];
    if (buffer) {
        self.frameHandler(buffer, textureId);
        CVPixelBufferRelease(buffer);
    }
    [self.registry textureFrameAvailable:textureId];
}
@end

// Only media-kit's registrar receives the texture adapter. Other plugins use
// their original registrars, and plugin registration remains generated by Flutter.
@interface KazumiPipRegistrar : NSObject <FlutterPluginRegistrar>
@property(nonatomic, strong) NSObject<FlutterPluginRegistrar> *registrar;
@property(nonatomic, strong) KazumiPipTextureRegistry *textureRegistry;
@property(nonatomic, weak) KazumiPipPluginRegistry *owner;
@end

@implementation KazumiPipRegistrar
- (NSObject<FlutterBinaryMessenger> *)messenger { return [self.registrar messenger]; }
- (NSObject<FlutterTextureRegistry> *)textures { return self.textureRegistry; }
- (UIViewController *)viewController { return self.registrar.viewController; }
- (void)publish:(NSObject *)value { [self.registrar publish:value]; }
- (void)addMethodCallDelegate:(NSObject<FlutterPlugin> *)delegate channel:(FlutterMethodChannel *)channel {
    self.owner.videoDelegate = delegate;
    KazumiPipVideoDelegate *adapter = [[KazumiPipVideoDelegate alloc] init];
    adapter.owner = self.owner;
    [self.registrar addMethodCallDelegate:adapter channel:channel];
}
- (void)addApplicationDelegate:(NSObject<FlutterPlugin> *)delegate {
    [self.registrar addApplicationDelegate:delegate];
}
- (void)addSceneDelegate:(NSObject<FlutterSceneLifeCycleDelegate> *)delegate {
    [self.registrar addSceneDelegate:delegate];
}
- (void)registerViewFactory:(NSObject<FlutterPlatformViewFactory> *)factory withId:(NSString *)factoryId {
    [self.registrar registerViewFactory:factory withId:factoryId];
}
- (void)registerViewFactory:(NSObject<FlutterPlatformViewFactory> *)factory
                   withId:(NSString *)factoryId
gestureRecognizersBlockingPolicy:(FlutterPlatformViewGestureRecognizersBlockingPolicy)policy {
    [self.registrar registerViewFactory:factory withId:factoryId gestureRecognizersBlockingPolicy:policy];
}
- (NSString *)lookupKeyForAsset:(NSString *)asset { return [self.registrar lookupKeyForAsset:asset]; }
- (NSString *)lookupKeyForAsset:(NSString *)asset fromPackage:(NSString *)package {
    return [self.registrar lookupKeyForAsset:asset fromPackage:package];
}
- (NSObject *)valuePublishedByPlugin:(NSString *)pluginKey {
    return [self.registrar valuePublishedByPlugin:pluginKey];
}
@end

@interface KazumiPipPluginRegistry ()
@property(nonatomic, strong) NSObject<FlutterPluginRegistry> *registry;
@property(nonatomic, strong) KazumiPipRegistrar *videoRegistrar;
@property(nonatomic, copy) void (^frameHandler)(CVPixelBufferRef, int64_t);
@end

@implementation KazumiPipPluginRegistry
- (instancetype)initWithRegistry:(NSObject<FlutterPluginRegistry> *)registry
                    frameHandler:(void (^)(CVPixelBufferRef, int64_t))frameHandler {
    self = [super init];
    if (self) {
        _registry = registry;
        _frameHandler = [frameHandler copy];
        _outputArguments = [NSMutableDictionary dictionary];
        _generations = [NSMutableDictionary dictionary];
        _softwareHandles = [NSMutableSet set];
        _recreatingHandles = [NSMutableSet set];
        _restorationCompletions = [NSMutableArray array];
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(restoreIfForeground)
            name:UIApplicationDidBecomeActiveNotification object:nil];
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(restoreIfForeground)
            name:UISceneDidActivateNotification object:nil];
    }
    return self;
}

- (NSObject<FlutterPluginRegistrar> *)registrarForPlugin:(NSString *)pluginKey {
    NSObject<FlutterPluginRegistrar> *registrar = [self.registry registrarForPlugin:pluginKey];
    if (![pluginKey isEqualToString:@"MediaKitVideoPlugin"] || !registrar) {
        return registrar;
    }
    KazumiPipTextureRegistry *textures = [[KazumiPipTextureRegistry alloc] init];
    textures.registry = [registrar textures];
    textures.textures = [NSMutableDictionary dictionary];
    textures.frameHandler = self.frameHandler;
    self.videoRegistrar = [[KazumiPipRegistrar alloc] init];
    self.videoRegistrar.registrar = registrar;
    self.videoRegistrar.textureRegistry = textures;
    self.videoRegistrar.owner = self;
    return self.videoRegistrar;
}

- (BOOL)hasPlugin:(NSString *)pluginKey { return [self.registry hasPlugin:pluginKey]; }
- (NSObject *)valuePublishedByPlugin:(NSString *)pluginKey {
    return [self.registry valuePublishedByPlugin:pluginKey];
}
- (CVPixelBufferRef)copyPixelBufferForTexture:(int64_t)textureId {
    return [self.videoRegistrar.textureRegistry.textures[@(textureId)] copyPixelBuffer];
}

- (void)handleVideoCall:(FlutterMethodCall *)call result:(FlutterResult)result {
    NSDictionary *args = [call.arguments isKindOfClass:[NSDictionary class]] ? call.arguments : nil;
    NSString *handle = args[@"handle"];
    if ([call.method isEqualToString:@"VideoOutputManager.Create"] && handle) {
        self.generations[handle] = @([self.generations[handle] unsignedIntegerValue] + 1);
        self.outputArguments[handle] = args;
        [self.softwareHandles removeObject:handle];
        BOOL software = self.softwareRendering ||
            (self.pendingRestore && UIApplication.sharedApplication.applicationState != UIApplicationStateActive);
        if (software && [args[@"configuration"][@"enableHardwareAcceleration"] boolValue]) {
            [self.softwareHandles addObject:handle];
            NSMutableDictionary *replacement = [args mutableCopy];
            NSMutableDictionary *configuration = [args[@"configuration"] mutableCopy];
            configuration[@"enableHardwareAcceleration"] = @NO;
            replacement[@"configuration"] = configuration;
            call = [FlutterMethodCall methodCallWithMethodName:call.method arguments:replacement];
        }
    } else if ([call.method isEqualToString:@"VideoOutputManager.SetSize"] && self.outputArguments[handle]) {
        NSMutableDictionary *saved = [self.outputArguments[handle] mutableCopy];
        NSMutableDictionary *configuration = [saved[@"configuration"] mutableCopy];
        configuration[@"width"] = args[@"width"];
        configuration[@"height"] = args[@"height"];
        saved[@"configuration"] = configuration;
        self.outputArguments[handle] = saved;
    } else if ([call.method isEqualToString:@"VideoOutputManager.Dispose"] && handle) {
        self.generations[handle] = @([self.generations[handle] unsignedIntegerValue] + 1);
        [self.outputArguments removeObjectForKey:handle];
        [self.softwareHandles removeObject:handle];
    }
    [self.videoDelegate handleMethodCall:call result:result];
}

// Recreate only the native video output. The mpv player, audio, source, playback
// position, decoder and shader settings all remain owned by the same player.
- (void)recreateOutput:(NSString *)handle completion:(void (^)(BOOL))completion {
    if ([self.recreatingHandles containsObject:handle] ||
        !self.videoOutputWillChange || !self.videoOutputDidChange) { completion(NO); return; }
    [self.recreatingHandles addObject:handle];
    NSUInteger generation = [self.generations[handle] unsignedIntegerValue];
    void (^finish)(BOOL) = ^(BOOL ready) {
        [self.recreatingHandles removeObject:handle];
        completion(ready);
        // Closing PiP may race with a software output still being created.
        // Revisit a successful transition that now needs foreground restoration.
        if (ready && !self.softwareRendering && [self.softwareHandles containsObject:handle] &&
            UIApplication.sharedApplication.applicationState == UIApplicationStateActive) {
            [self restoreIfForeground];
        }
        [self finishRestorationIfIdle];
    };
    void (^resume)(BOOL) = ^(BOOL created) {
        self.videoOutputDidChange(handle.longLongValue, ^(BOOL resumed) { finish(created && resumed); });
    };
    // Freeing an active mpv render context forcibly disables video. Suspend
    // the current video track first, then resume it after the new texture is registered.
    self.videoOutputWillChange(handle.longLongValue, ^(BOOL suspended) {
        if (!suspended) { finish(NO); return; }
        if (!self.outputArguments[handle] ||
            generation != [self.generations[handle] unsignedIntegerValue]) { resume(NO); return; }
        FlutterMethodCall *dispose = [FlutterMethodCall methodCallWithMethodName:@"VideoOutputManager.Dispose"
            arguments:@{@"handle": handle}];
        [self.videoDelegate handleMethodCall:dispose result:^(id value) {
            NSDictionary *saved = self.outputArguments[handle];
            if (!saved || generation != [self.generations[handle] unsignedIntegerValue] ||
                [value isKindOfClass:[FlutterError class]]) { resume(NO); return; }
            NSMutableDictionary *args = [saved mutableCopy];
            NSMutableDictionary *configuration = [saved[@"configuration"] mutableCopy];
            BOOL software = self.softwareRendering ||
                UIApplication.sharedApplication.applicationState != UIApplicationStateActive;
            if (software && [configuration[@"enableHardwareAcceleration"] boolValue]) {
                configuration[@"enableHardwareAcceleration"] = @NO;
                [self.softwareHandles addObject:handle];
            } else {
                [self.softwareHandles removeObject:handle];
            }
            args[@"configuration"] = configuration;
            FlutterMethodCall *create = [FlutterMethodCall methodCallWithMethodName:@"VideoOutputManager.Create"
                arguments:args];
            [self.videoDelegate handleMethodCall:create result:^(id result) {
                // Dart waits for VideoController.id to change before restoring vid;
                // media-kit's immediate Create reply precedes context initialization.
                resume(![result isKindOfClass:[FlutterError class]]);
            }];
        }];
    });
}

- (void)useSoftwareRenderingForHandle:(int64_t)handle completion:(void (^)(BOOL))completion {
    NSString *key = [NSString stringWithFormat:@"%lld", handle];
    NSDictionary *args = self.outputArguments[key];
    if (!args || !self.videoDelegate) { completion(NO); return; }
    self.softwareRendering = YES;
    self.pendingRestore = NO;
    if (![args[@"configuration"][@"enableHardwareAcceleration"] boolValue] ||
        [self.softwareHandles containsObject:key]) {
        completion(YES);
        return;
    }
    [self recreateOutput:key completion:completion];
}

- (void)restoreRenderingWithCompletion:(void (^)(void))completion {
    self.softwareRendering = NO;
    self.pendingRestore = self.softwareHandles.count > 0 || self.recreatingHandles.count > 0;
    [self.restorationCompletions addObject:[completion copy]];
    [self restoreIfForeground];
    [self finishRestorationIfIdle];
}

- (void)finishRestorationIfIdle {
    if (self.recreatingHandles.count > 0) return;
    NSArray<void (^)(void)> *completions = [self.restorationCompletions copy];
    [self.restorationCompletions removeAllObjects];
    for (void (^completion)(void) in completions) completion();
}

- (void)restoreIfForeground {
    if (self.softwareRendering || UIApplication.sharedApplication.applicationState != UIApplicationStateActive) return;
    self.pendingRestore = NO;
    for (NSString *handle in self.softwareHandles.allObjects) {
        [self recreateOutput:handle completion:^(BOOL restored) {}];
    }
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}
@end
