name: Bug 反馈
description: 提交一个 Bug 反馈。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        请详细填写以下内容~
  - type: textarea
    id: buginfo
    attributes:
      label: 在使用的时候发生了什么 Bug ？
      description: 并且，还请写出您是如何触发这个 Bug 的。
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: 您在使用哪个操作系统？
      multiple: false
      options:
        - Android
        - Windows
        - macOS / iOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: osver
    attributes:
      label: 请具体提供设备、版本号等信息。
      description: 例如，“Redmi K40S，Android 13”、“Windows 10 22H2” 等。
    validations:
      required: true
  - type: textarea
    id: hardware
    attributes:
      label: （选填）一些与 Bug 相关的硬件信息。
      description: （选填）例如，有视频播放问题，可以填写“显卡型号”、“显卡驱动版本”等。
  - type: textarea
    id: logs
    attributes:
      label: 日志信息
      description: 请在 “我的 - 关于 - 错误日志” 界面复制错误日志，并粘贴在这里。
      value: |
        <details open><summary>Log</summary>

        ```shell
        [在此处粘贴你的日志]
        ```

        </details>
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 提交前确认
      description: 在提交前，请确认以下内容
      options:
        - label: issue 列表中，没有我发现的这个 Bug
          required: true
        - label: 我正在使用最新版本的 Kazumi
          required: true
